const courses = [
  {
    id: 0,
    title: "Python Kursu",
    price: 66, 
    img_src: "https://picsum.photos/200/300/?blur",
    img_alt: "Python kursu görseli",
    quantity: 1,
    desc: "Python, veri bilimi, web geliştirme ve otomasyon gibi birçok alanda kullanılan popüler bir programlama dilidir.",
  },
  {
    id: 1,
    title: "JavaScript Kursu",
    price: 75,
    img_src: "https://picsum.photos/200/300/?random=1",
    img_alt: "JavaScript kursu görseli",
    quantity: 1,
    desc: "JavaScript, web geliştirme için vazgeçilmez bir dildir ve etkileşimli web uygulamaları oluşturmak için kullanılır.",
  },
  {
    id: 2,
    title: "Java Kursu",
    price: 80,
    img_src: "https://picsum.photos/200/300/?random=2",
    img_alt: "Java kursu görseli",
    quantity: 1,
    desc: "Java, kurumsal uygulamalar ve Android uygulama geliştirme için yaygın olarak kullanılan güçlü bir programlama dilidir.",
  },
  {
    id: 3,
    title: "C# Kursu",
    price: 70,
    img_src: "https://picsum.photos/200/300/?random=3",
    img_alt: "C# kursu görseli",
    quantity: 1,
    desc: "C#, Microsoft tarafından geliştirilmiş, özellikle oyun ve masaüstü uygulamaları için kullanılan bir dildir.",
  },
  {
    id: 4,
    title: "PHP Kursu",
    price: 65,
    img_src: "https://picsum.photos/200/300/?random=4",
    img_alt: "PHP kursu görseli",
    quantity: 1,
    desc: "PHP, dinamik web siteleri ve uygulamaları geliştirmek için yaygın olarak kullanılan bir sunucu tarafı programlama dilidir.",
  },
  {
    id: 5,
    title: "Ruby Kursu",
    price: 72,
    img_src: "https://picsum.photos/200/300/?random=5",
    img_alt: "Ruby kursu görseli",
    quantity: 1,
    desc: "Ruby, okunabilir ve sezgisel bir sözdizimi sunan, web geliştirme için popüler bir programlama dilidir.",
  },
  {
    id: 6,
    title: "Swift Kursu",
    price: 85,
    img_src: "https://picsum.photos/200/300/?random=6",
    img_alt: "Swift kursu görseli",
    quantity: 1,
    desc: "Swift, Apple tarafından geliştirilmiş, iOS ve macOS uygulamaları için modern ve hızlı bir programlama dilidir.",
  },
  {
    id: 7,
    title: "Go Kursu",
    price: 90,
    img_src: "https://picsum.photos/200/300/?random=7",
    img_alt: "Go kursu görseli",
    quantity: 1,
    desc: "Go, Google tarafından geliştirilen, yüksek performanslı ve verimli bir sistem programlama dilidir.",
  },
  {
    id: 8,
    title: "Kotlin Kursu",
    price: 78,
    img_src: "https://picsum.photos/200/300/?random=8",
    img_alt: "Kotlin kursu görseli",
    quantity: 1,
    desc: "Kotlin, Java ile tamamen uyumlu olan, modern ve çok yönlü bir Android geliştirme dilidir.",
  },
  {
    id: 9,
    title: "Dart Kursu",
    price: 68,
    img_src: "https://picsum.photos/200/300/?random=9",
    img_alt: "Dart kursu görseli",
    quantity: 1,
    desc: "Dart, özellikle Flutter ile mobil uygulama geliştirmek için kullanılan bir dildir.",
  },
  {
    id: 10,
    title: "R Kursu",
    price: 82,
    img_src: "https://picsum.photos/200/300/?random=10",
    img_alt: "R kursu görseli",
    quantity: 1,
    desc: "R, istatistiksel analiz ve veri görselleştirme için yaygın olarak kullanılan bir programlama dilidir.",
  }
];

export default courses;
